language: node_js
node_js:
  - "14"

env:
  # - WEBPACK_VERSION=3 HTML_PLUGIN_VERSION=3
  - WEBPACK_VERSION=4 HTML_PLUGIN_VERSION=3
  - WEBPACK_VERSION=4 HTML_PLUGIN_VERSION=4

install: 
  - npm install
  - npm install -D webpack@$WEBPACK_VERSION || true
  - npm install -D html-webpack-plugin@$HTML_PLUGIN_VERSION || true

script: 
  - npm test
  - npm run build

deploy:
  skip_cleanup: true
  on:
    repo: ShaolinWang/html-webpack-assets-path-plugin
    node: "14"
    tags: true
    branch: main
    if: env(WEBPACK_VERSION)=4 AND env(HTML_PLUGIN_VERSION)=4
  provider: npm
  email: "wangshaolin3@jd.com"